question_data = [
        {
            "category": "Science: Computers",
            "type": "multiple",
            "difficulty": "easy",
            "question": "In any programming language, what is the most common way to iterate through an array?",
            "correct_answer": "&#039;For&#039; loops",
         "incorrect_answers": ["&#039;If&#039; Statements", "&#039;Do-while&#039; loops", "&#039;While&#039; loops"]},
        {"category": "Science: Computers", "type": "multiple", "difficulty": "easy",
         "question": "According to the International System of Units, how many bytes are in a kilobyte of RAM?",
         "correct_answer": "1000", "incorrect_answers": ["512", "1024", "500"]},
        {"category": "Science: Computers", "type": "multiple", "difficulty": "easy",
         "question": "When Gmail first launched, how much storage did it provide for your email?",
         "correct_answer": "1GB",
         "incorrect_answers": ["512MB", "5GB", "Unlimited"]},
        {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
         "question": "The logo for Snapchat is a Bell.", "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Science: Computers", "type": "multiple", "difficulty": "easy",
         "question": "What is the most preferred image format used for logos in the Wikimedia database?",
         "correct_answer": ".svg", "incorrect_answers": [".png", ".jpeg", ".gif"]},
        {"category": "Science: Computers", "type": "multiple", "difficulty": "easy",
         "question": "In web design, what does CSS stand for?", "correct_answer": "Cascading Style Sheet",
         "incorrect_answers": ["Counter Strike: Source", "Corrective Style Sheet", "Computer Style Sheet"]},
        {"category": "Science: Computers", "type": "multiple", "difficulty": "easy",
         "question": "What is the domain name for the country Tuvalu?", "correct_answer": ".tv",
         "incorrect_answers": [".tu", ".tt", ".tl"]},
        {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
         "question": "&quot;HTML&quot; stands for Hypertext Markup Language.", "correct_answer": "True",
         "incorrect_answers": ["False"]}, {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                                           "question": "The Windows ME operating system was released in the year 2000.",
                                           "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Science: Computers", "type": "multiple", "difficulty": "easy",
         "question": "What language does Node.js use?", "correct_answer": "JavaScript",
         "incorrect_answers": ["Java", "Java Source", "Joomla Source Code"]}]
